import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "The Vault",
    short_name: "Vault",
    description: "The Vault — a place for everything.",
    start_url: "/",
    display: "standalone",
    background_color: "#f3eee5",
    theme_color: "#f3eee5",
    orientation: "portrait",
    // Generated by app/icon0.tsx (192) and app/icon1.tsx (512).
    // Next serves them at /icon0 and /icon1.
    icons: [
      {
        src: "/icon0",
        sizes: "192x192",
        type: "image/png",
      },
      {
        src: "/icon1",
        sizes: "512x512",
        type: "image/png",
      },
      {
        src: "/icon1",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
