// Fallback data so the UI renders before the Sheet migration runs.
// Removed once `items` is populated.

import type { Item } from "./types";

const now = () => new Date().toISOString();

export const fixtureItems: Item[] = [
  // COUNTER (admin pile)
  {
    id: "fx-drawer-1",
    box: "COUNTER",
    title: "File Q1 sales tax (PCS)",
    area: "ECO",
    minutes: 45,
    urgent: true,
    must: true,
    pinned: false,
    createdAt: now(),
    modifiedAt: now(),
  },
  {
    id: "fx-drawer-2",
    box: "COUNTER",
    title: "Cruise contract follow-up",
    area: "SWB",
    minutes: 20,
    urgent: true,
    must: false,
    pinned: false,
    createdAt: now(),
    modifiedAt: now(),
  },
  {
    id: "fx-drawer-3",
    box: "COUNTER",
    title: "Schedule mom's quarterly review",
    area: "FF",
    minutes: 30,
    urgent: false,
    must: true,
    pinned: false,
    createdAt: now(),
    modifiedAt: now(),
  },
  {
    id: "fx-drawer-4",
    box: "COUNTER",
    title: "Update health insurance",
    area: "HEALTH",
    minutes: 25,
    urgent: false,
    must: true,
    pinned: false,
    createdAt: now(),
    modifiedAt: now(),
  },
  // ATM (energy picks)
  {
    id: "fx-till-1",
    box: "ATM",
    title: "Outline Chapter 6 of the new book",
    energy: "CREATIVE",
    category: "Writing",
    minutes: 60,
    urgent: false,
    must: false,
    pinned: false,
    createdAt: now(),
    modifiedAt: now(),
  },
  {
    id: "fx-till-2",
    box: "ATM",
    title: "Reorganize PCS marketing calendar",
    energy: "PROB-SOLV",
    category: "Marketing",
    minutes: 45,
    urgent: false,
    must: false,
    pinned: false,
    createdAt: now(),
    modifiedAt: now(),
  },
  {
    id: "fx-till-3",
    box: "ATM",
    title: "Quick outreach to 3 cruise contacts",
    energy: "PROB-SOLV",
    category: "Sales",
    minutes: 30,
    urgent: false,
    must: false,
    pinned: false,
    createdAt: now(),
    modifiedAt: now(),
  },
  // DROP (untriaged)
  {
    id: "fx-drop-1",
    box: "DROP",
    title: "Idea: gift guide for cruise crowd",
    urgent: false,
    must: false,
    pinned: false,
    createdAt: now(),
    modifiedAt: now(),
  },
  {
    id: "fx-drop-2",
    box: "DROP",
    title: "Ask Ron about Q3 forecast",
    urgent: false,
    must: false,
    pinned: false,
    createdAt: now(),
    modifiedAt: now(),
  },
  // PCS_IDEAS
  {
    id: "fx-pcs-1",
    box: "PCS_IDEAS",
    title: "Subscription clay box",
    potential: 4,
    minutes: 480,
    person: "Tracy",
    category: "Product",
    tag: "Creative",
    urgent: false,
    must: false,
    pinned: false,
    createdAt: now(),
    modifiedAt: now(),
  },
];
